server:
  port: 8084

spring:
  application:
    name: notification-service
  redis:
    host: ${REDIS_URL:localhost}
    port: 6379

app:
  notification:
    default-ttl: 86400  # 24 hours in seconds

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.fiapx.notification: DEBUG
    org.springframework.web: DEBUG 