server:
  port: 8081

spring:
  application:
    name: upload-service
  redis:
    host: ${REDIS_URL:localhost}
    port: 6379
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

app:
  upload:
    max-file-size: 524288000  # 500MB in bytes
    allowed-extensions: mp4,avi,mov,mkv,wmv,flv,webm

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.fiapx.upload: DEBUG
    org.springframework.web: DEBUG 