server:
  port: 8082

spring:
  application:
    name: processing-service
  redis:
    host: ${REDIS_URL:localhost}
    port: 6379

app:
  processing:
    output-dir: outputs
    processing-dir: processing
  notification-service-url: ${NOTIFICATION_SERVICE_URL:http://notification-service:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.fiapx.processing: DEBUG
    org.springframework.web: DEBUG 